# Generated by Django 5.0 on 2025-01-25 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Congregação')),
                ('deskrisau', models.TextField(verbose_name='Deskrisau')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='congregacao/', verbose_name='Imajen / Logo')),
                ('file', models.FileField(blank=True, null=True, upload_to='congregacoes/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Congregação',
                'verbose_name_plural': 'Congregações',
            },
        ),
        migrations.CreateModel(
            name='EisSeminaristaExReligioso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Naran Completo')),
                ('estadoeivil', models.DateField(blank=True, null=True, verbose_name='Estado Civil')),
                ('contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='contacto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eis_seminaristas_ex_religiosos/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Eis-Seminarista/Ex Religioso/a',
                'verbose_name_plural': 'Eis-Seminaristas/Ex Religiosos/as',
            },
        ),
        migrations.CreateModel(
            name='EskolaCatolico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Escola Católica')),
                ('deskrisau', models.TextField(verbose_name='Deskrisau')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eskolacatolico/', verbose_name='Imajen / Logo')),
                ('file', models.FileField(blank=True, null=True, upload_to='eskolas/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Escola Católica',
                'verbose_name_plural': 'Escolas Católicas',
            },
        ),
        migrations.CreateModel(
            name='GrupuCategorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Grupo Categorial')),
                ('deskrisau', models.TextField(verbose_name='Deskrisau')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='grupucategorial/', verbose_name='Imajen / Logo')),
                ('file', models.FileField(blank=True, null=True, upload_to='grupus/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Grupo Categorial',
                'verbose_name_plural': 'Grupos Categoriais',
            },
        ),
        migrations.CreateModel(
            name='PadreMadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Naran Completo')),
                ('tipo', models.CharField(choices=[('padre', 'Padre Liquiçá oan'), ('madre', 'Madre Liquiçá oan')], max_length=10, verbose_name='Tipo')),
                ('fatinnodataordenacao', models.DateField(blank=True, null=True, verbose_name='Fatin no data Ordenação')),
                ('fatinservico', models.DateField(blank=True, null=True, verbose_name='Fatin Serviço')),
                ('contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='padres_madres/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Padre/Madre',
                'verbose_name_plural': 'Padres/Madres',
            },
        ),
        migrations.CreateModel(
            name='PerfilParoquiaSAJOBRIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda')),
                ('amu', models.TextField(blank=True, null=True, verbose_name='Amu Parokia')),
                ('naran_parokia', models.TextField(blank=True, null=True, verbose_name='Naran Parokia')),
                ('sigla_parokia', models.TextField(blank=True, null=True, verbose_name='Sigla Parokia')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address Parokia')),
                ('email', models.TextField(blank=True, null=True, verbose_name='Email Parokia')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Phone Parokia')),
                ('introdusaun', models.TextField(blank=True, null=True, verbose_name='Introdusaun')),
                ('visao_geral', models.TextField(verbose_name='Visão Geral')),
                ('visao_especifica', models.TextField(verbose_name='Visão Específica')),
                ('missao', models.TextField(verbose_name='Missão')),
                ('istoria_existencia', models.TextField(verbose_name='Istoria Existencia Paróquia SAJOBRIL')),
                ('situacao_geral', models.TextField(verbose_name='Situação Geral Paróquia SJB Liquiçá')),
                ('area_geografica', models.ImageField(blank=True, null=True, upload_to='area_geografica_images/', verbose_name='Área Geográfica Paróquia São João de Brito Liquiçá')),
                ('lian_nebe_usa', models.TextField(verbose_name='Lian nebé usa iha actividade liturgia')),
                ('ecp', models.ImageField(blank=True, null=True, upload_to='ecp_images/', verbose_name='Estrutura Conselho Pastoral Paróquia (CPP)')),
                ('cep', models.ImageField(blank=True, null=True, upload_to='ecp_images/', verbose_name='Estrutura Conselho Económico Paroquial (CEP)')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Perfil Paroquial SAJOBRIL',
                'verbose_name_plural': 'Perfis Paroquiais SAJOBRIL',
            },
        ),
        migrations.CreateModel(
            name='ProfessorReligiaoCatolico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Naran Completo')),
                ('fatinserviço', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fatin Serviço')),
                ('estatuto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estatuto (Recrutado)')),
                ('kontaktu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontaktu')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='professores_religiao_catolico/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Professor/a Religião Católico',
                'verbose_name_plural': 'Professores/as Religião Católico',
            },
        ),
    ]
