# Generated by Django 5.0.6 on 2024-09-09 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EisSeminaristaExReligioso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eis_seminaristas_ex_religiosos/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Eis-Seminarista/Ex Religioso/a',
                'verbose_name_plural': 'Eis-Seminaristas/Ex Religiosos/as',
            },
        ),
        migrations.CreateModel(
            name='PadreMadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('padre', 'Padre Liquiçá oan'), ('madre', 'Madre Liquiçá oan')], max_length=10, verbose_name='Tipo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='padres_madres/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Padre/Madre',
                'verbose_name_plural': 'Padres/Madres',
            },
        ),
        migrations.CreateModel(
            name='PerfilParoquiaSAJOBRIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Data muda')),
                ('visao_geral', models.TextField(verbose_name='Visão Geral')),
                ('visao_especifica', models.TextField(verbose_name='Visão Específica')),
                ('missao', models.TextField(verbose_name='Missão')),
                ('istoria_existencia', models.TextField(verbose_name='Istoria Existencia Paróquia SAJOBRIL')),
                ('situacao_geral', models.TextField(verbose_name='Situação Geral Paróquia SJB Liquiçá')),
                ('area_geografica', models.ImageField(blank=True, null=True, upload_to='area_geografica_images/', verbose_name='Área Geográfica Paróquia São João de Brito Liquiçá')),
                ('lian_nebe_usa', models.TextField(verbose_name='Lian nebé usa iha actividade liturgia')),
                ('ecp', models.ImageField(blank=True, null=True, upload_to='ecp_images/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Perfil Paroquial SAJOBRIL',
                'verbose_name_plural': 'Perfis Paroquiais SAJOBRIL',
            },
        ),
        migrations.CreateModel(
            name='GrupuCategorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Grupo Categorial')),
                ('deskrisau', models.TextField(verbose_name='Deskrisau')),
                ('file', models.FileField(blank=True, null=True, upload_to='grupus/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
                ('perfil_paroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupus', to='perfil.perfilparoquiasajobril')),
            ],
            options={
                'verbose_name': 'Grupo Categorial',
                'verbose_name_plural': 'Grupos Categoriais',
            },
        ),
        migrations.CreateModel(
            name='EskolaCatolico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Escola Católica')),
                ('deskrisau', models.TextField(verbose_name='Deskrisau')),
                ('file', models.FileField(blank=True, null=True, upload_to='eskolas/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
                ('perfil_paroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eskolas', to='perfil.perfilparoquiasajobril')),
            ],
            options={
                'verbose_name': 'Escola Católica',
                'verbose_name_plural': 'Escolas Católicas',
            },
        ),
        migrations.CreateModel(
            name='Congregacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Congregação')),
                ('deskrisau', models.TextField(verbose_name='Deskrisau')),
                ('file', models.FileField(blank=True, null=True, upload_to='congregacoes/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
                ('perfil_paroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congregacoes', to='perfil.perfilparoquiasajobril')),
            ],
            options={
                'verbose_name': 'Congregação',
                'verbose_name_plural': 'Congregações',
            },
        ),
        migrations.CreateModel(
            name='ProfessorReligiaoCatolico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Apaga')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data kria')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Data muda')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='professores_religiao_catolico/')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi')),
            ],
            options={
                'verbose_name': 'Professor/a Religião Católico',
                'verbose_name_plural': 'Professores/as Religião Católico',
            },
        ),
    ]
