# Generated by Django 5.0.6 on 2024-09-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregacao',
            name='perfil_paroquia',
        ),
        migrations.RemoveField(
            model_name='eskolacatolico',
            name='perfil_paroquia',
        ),
        migrations.RemoveField(
            model_name='grupucategorial',
            name='perfil_paroquia',
        ),
    ]
