# Generated by Django 5.0 on 2025-01-25 16:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='introdusaun',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Introdusaun'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='istoria_existencia',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Istoria Existencia Paróquia SAJOBRIL'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='lian_nebe_usa',
            field=models.TextField(blank=True, null=True, verbose_name='Lian nebé usa iha actividade liturgia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='missao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Missão'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='situacao_geral',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Situação Geral Paróquia SJB Liquiçá'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='visao_especifica',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Visão Específica'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='visao_geral',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Visão Geral'),
        ),
    ]
