# Generated by Django 5.0.6 on 2024-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_congregacao_perfil_paroquia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilparoquiasajobril',
            name='cep',
            field=models.ImageField(blank=True, null=True, upload_to='ecp_images/', verbose_name='Estrutura Conselho Económico Paroquial (CEP)'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='ecp',
            field=models.ImageField(blank=True, null=True, upload_to='ecp_images/', verbose_name='Estrutura Conselho Pastoral Paróquia (CPP)'),
        ),
    ]
