# Generated by Django 5.0 on 2025-01-25 16:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfilparoquiasajobril_introdusaun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Parokia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='amu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Amu Parokia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Parokia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='introdusaun',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Introdusaun'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='naran_parokia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naran Parokia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Parokia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='sigla_parokia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sigla Parokia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='visao_especifica',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Visão Específica'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='visao_geral',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Visão Geral'),
        ),
    ]
