# Generated by Django 5.0.6 on 2024-10-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_perfilparoquiasajobril_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregacao',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='congregacao/', verbose_name='Imajen / Logo'),
        ),
        migrations.AddField(
            model_name='eskolacatolico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eskolacatolico/', verbose_name='Imajen / Logo'),
        ),
        migrations.AddField(
            model_name='grupucategorial',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='grupucategorial/', verbose_name='Imajen / Logo'),
        ),
    ]
