# Generated by Django 5.0 on 2025-02-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_perfilparoquiasajobril_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eisseminaristaexreligioso',
            name='estadoeivil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='padremadre',
            name='fatinnodataordenacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fatin no data Ordenação'),
        ),
    ]
