# Generated by Django 5.0 on 2025-01-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_congregacao_imagen_eskolacatolico_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilparoquiasajobril',
            name='amu',
            field=models.TextField(blank=True, null=True, verbose_name='Amu'),
        ),
    ]
