# Generated by Django 5.0 on 2025-02-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_eisseminaristaexreligioso_estadoeivil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padremadre',
            name='fatinservico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fatin Serviço'),
        ),
    ]
