# Generated by Django 5.0 on 2025-01-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_perfilparoquiasajobril_amu'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilparoquiasajobril',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='perfilparoquiasajobril',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='perfilparoquiasajobril',
            name='introdusaun',
            field=models.TextField(blank=True, null=True, verbose_name='Introdusaun'),
        ),
        migrations.AddField(
            model_name='perfilparoquiasajobril',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='amu',
            field=models.TextField(blank=True, null=True, verbose_name='Amu Parokia'),
        ),
    ]
