# Generated by Django 5.0 on 2025-02-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_padremadre_fatinservico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregacao',
            name='deskrisau',
        ),
        migrations.AddField(
            model_name='congregacao',
            name='fatinsuperioracongregacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fatin\tSuperiora Congregação'),
        ),
        migrations.AddField(
            model_name='congregacao',
            name='nocontacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='No. Contacto'),
        ),
        migrations.AddField(
            model_name='congregacao',
            name='superioracongregacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Superiora Congregação'),
        ),
        migrations.AlterField(
            model_name='congregacao',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Naran Congregação'),
        ),
    ]
