# Generated by Django 5.0 on 2025-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_remove_congregacao_deskrisau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupucategorial',
            name='deskrisau',
        ),
        migrations.AddField(
            model_name='grupucategorial',
            name='chefegrupo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chefe Grupo'),
        ),
        migrations.AddField(
            model_name='grupucategorial',
            name='nocontacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='No. Contacto'),
        ),
        migrations.AddField(
            model_name='grupucategorial',
            name='totalmembro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total Membro'),
        ),
        migrations.AlterField(
            model_name='grupucategorial',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Naran Grupo Categoriais'),
        ),
    ]
