# Generated by Django 5.0 on 2025-01-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_perfilparoquiasajobril_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilparoquiasajobril',
            name='naran_parokia',
            field=models.TextField(blank=True, null=True, verbose_name='Naran Parokia'),
        ),
        migrations.AddField(
            model_name='perfilparoquiasajobril',
            name='sigla_parokia',
            field=models.TextField(blank=True, null=True, verbose_name='Sigla Parokia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address Parokia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Email Parokia'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='Phone Parokia'),
        ),
    ]
