# Generated by Django 5.0 on 2025-01-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_perfilparoquiasajobril_naran_parokia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacao',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='congregacao',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='congregacao',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='eisseminaristaexreligioso',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='eisseminaristaexreligioso',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='eisseminaristaexreligioso',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='eskolacatolico',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='eskolacatolico',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='eskolacatolico',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='grupucategorial',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='grupucategorial',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='grupucategorial',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='padremadre',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='padremadre',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='padremadre',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='professorreligiaocatolico',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='professorreligiaocatolico',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='professorreligiaocatolico',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
    ]
