# Generated by Django 5.0 on 2025-02-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_remove_grupucategorial_deskrisau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eskolacatolico',
            name='deskrisau',
        ),
        migrations.AddField(
            model_name='eskolacatolico',
            name='fatinestabelecimento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fatin Estabelecimento'),
        ),
        migrations.AddField(
            model_name='eskolacatolico',
            name='nocontacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='No. Kontaktu'),
        ),
        migrations.AlterField(
            model_name='eskolacatolico',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Naran Escola'),
        ),
    ]
