# Generated by Django 5.0 on 2025-02-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_remove_eskolacatolico_deskrisau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilparoquiasajobril',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='perfilparoquiasajobril',
            name='ecp',
        ),
        migrations.AddField(
            model_name='perfilparoquiasajobril',
            name='ecppcep',
            field=models.ImageField(blank=True, null=True, upload_to='ecp_images/', verbose_name='ESTRUTURA CPP-CEP PAROQUIA SÃO JOÃO DE BRITO LIQUIÇÁ'),
        ),
    ]
