# Generated by Django 5.0 on 2025-02-01 12:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_remove_perfilparoquiasajobril_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='introdusaun',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Introdusaun'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='visao_especifica',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Visão Específica'),
        ),
        migrations.AlterField(
            model_name='perfilparoquiasajobril',
            name='visao_geral',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Visão Geral'),
        ),
    ]
