# Generated by Django 5.0.6 on 2024-10-30 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Comissaun')),
                ('deskrisaun', models.TextField(verbose_name='Deskrisaun')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Info')),
            ],
            options={
                'verbose_name': 'Palnu Dezenvolvimentu',
                'verbose_name_plural': 'Palnu Dezenvolvimentu',
            },
        ),
        migrations.CreateModel(
            name='DettaluPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='planu_comisaun_files/')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('planu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaluplano_set', to='planodesenvolvimento.planu')),
            ],
            options={
                'verbose_name': 'Planu dezenvolvimentu Detallu',
                'verbose_name_plural': 'Planu dezenvolvimentu Detallu',
            },
        ),
    ]
