# Generated by Django 5.0.6 on 2024-10-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodesenvolvimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planu',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Planu dezenvolvimentu ba  ?'),
        ),
    ]
