# Generated by Django 5.0.6 on 2024-10-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='centro_pastoral_logos/')),
                ('historia_existencia', models.TextField()),
                ('estrutura', models.TextField()),
                ('estasaun_misionario', models.TextField()),
            ],
        ),
    ]
