# Generated by Django 5.0.6 on 2024-10-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centropastoral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centropastoral',
            name='estrutura',
            field=models.ImageField(upload_to='centro_pastoral_estrutura/'),
        ),
    ]
