# Generated by Django 5.0.6 on 2024-10-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centropastoral', '0002_alter_centropastoral_estrutura'),
    ]

    operations = [
        migrations.AddField(
            model_name='centropastoral',
            name='estruturabairo',
            field=models.ImageField(blank=True, null=True, upload_to='centro_pastoral_estrutura/', verbose_name='Estrutura Bairo sira'),
        ),
        migrations.AlterField(
            model_name='centropastoral',
            name='estrutura',
            field=models.ImageField(blank=True, null=True, upload_to='centro_pastoral_estrutura/', verbose_name='Estrutura Estasaun Misionario'),
        ),
    ]
