# Generated by Django 5.0.6 on 2024-10-30 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comissaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Comissaun')),
                ('deskrisaun', models.TextField(verbose_name='Deskrisaun')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='comissaun_logos/')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Info')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
            },
        ),
        migrations.CreateModel(
            name='PlanuComisaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='planu_comisaun_files/')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('comissaun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planus', to='comissaun.comissaun')),
            ],
            options={
                'verbose_name': 'Plano da Comissão',
                'verbose_name_plural': 'Planos da Comissão',
            },
        ),
    ]
