# Generated by Django 5.0 on 2025-01-24 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissaun', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comissaun',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AddField(
            model_name='comissaun',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AddField(
            model_name='comissaun',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AddField(
            model_name='comissaun',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi'),
        ),
        migrations.AddField(
            model_name='planucomisaun',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AddField(
            model_name='planucomisaun',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AddField(
            model_name='planucomisaun',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AddField(
            model_name='planucomisaun',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kria husi'),
        ),
    ]
