# Generated by Django 5.0.6 on 2024-10-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_remove_missa_day_remove_missa_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentu',
            name='service',
        ),
        migrations.AddField(
            model_name='atendimentu',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Requerementu'),
        ),
        migrations.AlterField(
            model_name='atendimentu',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Titulu'),
        ),
    ]
