# Generated by Django 5.0 on 2025-01-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_remove_atendimentu_service_atendimentu_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualplan',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='annualplan',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='annualplan',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='atendimentu',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='atendimentu',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='atendimentu',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='aunsiu',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='aunsiu',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='aunsiu',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='eventu',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='eventu',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='eventu',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='missa',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='missa',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='missa',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data kria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data muda'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Apaga'),
        ),
    ]
